ListenIP: "127.0.0.1"
ListenPort: "8080"
Dashboard:
  Title: "Freelance Bangladesh"
Keycloak:
  BaseUrl: "http://localhost:9990"
  Realm: "freelance-bangladesh"
  RestApi:
    ClientId: ""
    ClientSecret: ""
Database:
  Host: ""
  Port: ""
  User: ""
  Password: ""
  Name: ""
