ListenIP: "0.0.0.0"
ListenPort: "8080"
Dashboard:
  Title: "Freelance Bangladesh"
Keycloak:
  BaseUrl: "http://0.0.0.0:9990"
  Realm: "freelance-bangladesh"
  RestApi:
    ClientId: ""
    ClientSecret: ""
Database:
  Host: "127.0.0.1"
  Port: "5432"
  User: ""
  Password: ""
  Name: ""
