ListenIP: "0.0.0.0"
ListenPort: "5000"
Dashboard:
  Title: "Freelance Bangladesh"
Keycloak:
  BaseUrl: "http://127.0.0.1:8080"
  Realm: "freelance-bangladesh"
  RestApi:
    ClientId: ""
    ClientSecret: ""
Database:
  Host: "127.0.0.1"
  Port: "5432"
  User: ""
  Password: ""
  Name: ""
