services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5434:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - postgres_network
  
  postgres-db:
    image: postgres:16.4
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${API_DATABASE_NAME}
      POSTGRES_USER: ${API_DATABASE_USER}
      POSTGRES_PASSWORD: ${API_DATABASE_PASSWORD}
    ports:
      - ${API_DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres_network
  
  keycloak-db:
    image: postgres:16.4
    container_name: keycloak-db
    environment:
      POSTGRES_DB: ${KEYCLOAK_DATABASE_NAME}
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/${KEYCLOAK_DATABASE_NAME} # Note: keycloak-db is the address of the database
      KC_DB_USERNAME: ${KEYCLOAK_DATABASE_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    ports:
      - 9990:8080
    volumes:
      - ./keycloak/:/opt/keycloak/data/import
    restart: unless-stopped
    depends_on:
      - keycloak-db
    command: -v start-dev --import-realm
    networks:
      - keycloak_network

volumes:
  pgadmin_data:
    driver: local
  postgres_data:
    driver: local
  keycloak_db_data:
    driver: local
  # keycloak_data:
  #   driver: local

networks:
  postgres_network:
    driver: bridge
  keycloak_network:
    driver: bridge