export POSTGRES_DB=keycloak-db
export POSTGRES_USER=
export POSTGRES_PASSWORD=

export KEYCLOAK_ADMIN=
export KEYCLOAK_ADMIN_PASSWORD=

export API_KEYCLOAK_BASEURL=http://localhost:9990
export API_KEYCLOAK_REALM=freelance-bangladesh
export API_KEYCLOAK_RESTAPI_CLIENTID=
export API_KEYCLOAK_RESTAPI_CLIENTSECRET=
