export KEYCLOAK_DATABASE_USER=xxx
export KEYCLOAK_DATABASE_PASSWORD=xxx
export KEYCLOAK_DATABASE_NAME=keycloak-db
export KEYCLOAK_ADMIN=xxx
export KEYCLOAK_ADMIN_PASSWORD=xxx

export PGADMIN_EMAIL=xxx
export PGADMIN_PASSWORD=xxx

export API_KEYCLOAK_BASEURL=http://127.0.0.1:9990
export API_KEYCLOAK_REALM=freelance-bangladesh
export API_KEYCLOAK_RESTAPI_CLIENTID=backend-api
export API_KEYCLOAK_RESTAPI_CLIENTSECRET=xxx

export API_DATABASE_HOST=127.0.0.1 # only for running locally
export API_DATABASE_PORT=5432
export API_DATABASE_USER=admin
export API_DATABASE_PASSWORD=xxx
export API_DATABASE_NAME=freelance-db
