export KEYCLOAK_DATABASE_USER=
export KEYCLOAK_DATABASE_PASSWORD=
export KEYCLOAK_DATABASE_NAME=keycloak-db

export KEYCLOAK_ADMIN=admin
export KEYCLOAK_ADMIN_PASSWORD=admin

export PGADMIN_EMAIL=
export PGADMIN_PASSWORD=

export API_KEYCLOAK_BASEURL=http://localhost:9990
export API_KEYCLOAK_REALM=freelance-bangladesh
export API_KEYCLOAK_RESTAPI_CLIENTID=backend-api
export API_KEYCLOAK_RESTAPI_CLIENTSECRET=

export API_DATABASE_HOST=127.0.0.1
export API_DATABASE_PORT=5433
export API_DATABASE_USER=admin@freelance-bangladesh.com
export API_DATABASE_PASSWORD=
export API_DATABASE_NAME=freelance-db
